pipeline {
    agent any
    stages {
        stage('Create virtual env and install all requirements') {
            steps {
                sh '''
                python3 -m venv venv
                ./venv/bin/pip3 install -r requirements.txt
                '''
            }
        }
        stage('Install Playwright browsers') {
            steps {
                sh '''
                ./venv/bin/playwright install
                '''
            }
        }
        stage('Start Playwright pytest tests') {
            steps {
                sh '''
                ./venv/bin/pytest
                '''
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}
